### ISSUE TITLE
can't send message to dialog

### ISSUE THREAD

**Issue by MohammadAsef** [QuickBlox/quickblox-flutter-samples#8] opened 2021-12-19 12:02 UTC
Hello, I created user and logged in successfully even can create dialog fine but when I want to send message this happened to me please help me soon it's urgent.
`````
E/MethodChannel#FlutterQBChatChannel(23158): Failed to handle method call
E/MethodChannel#FlutterQBChatChannel(23158): java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
E/MethodChannel#FlutterQBChatChannel(23158): 	at com.quickblox.quickblox_sdk.chat.ChatModule.sendMessage(ChatModule.java:681)
E/MethodChannel#FlutterQBChatChannel(23158): 	at com.quickblox.quickblox_sdk.chat.ChatModule.handleMethod(ChatModule.java:148)
E/MethodChannel#FlutterQBChatChannel(23158): 	at com.quickblox.quickblox_sdk.chat.-$$Lambda$DVgH6HdFVfXJ1jon6MQo8bSJBRA.onMethodCall(Unknown Source:2)
E/MethodChannel#FlutterQBChatChannel(23158): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:262)
E/MethodChannel#FlutterQBChatChannel(23158): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:178)
E/MethodChannel#FlutterQBChatChannel(23158): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$handleMessageFromDart$0$DartMessenger(DartMessenger.java:206)
E/MethodChannel#FlutterQBChatChannel(23158): 	at io.flutter.embedding.engine.dart.-$$Lambda$DartMessenger$6ZD1MYkhaLxyPjtoFDxe45u43DI.run(Unknown Source:12)
E/MethodChannel#FlutterQBChatChannel(23158): 	at android.os.Handler.handleCallback(Handler.java:873)
E/MethodChannel#FlutterQBChatChannel(23158): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#FlutterQBChatChannel(23158): 	at android.os.Looper.loop(Looper.java:193)
E/MethodChannel#FlutterQBChatChannel(23158): 	at android.app.ActivityThread.main(ActivityThread.java:6669)
E/MethodChannel#FlutterQBChatChannel(23158): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#FlutterQBChatChannel(23158): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
E/MethodChannel#FlutterQBChatChannel(23158): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
I/flutter (23158): java.lang.String cannot be cast to java.lang.Long//null//java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Long
`````

**Comment by MohammadAsef** [comment] 2021-12-19 12:46
I figured it's because of dateSent property. if I leave it to null error will ocuured but if I set it to some string it show this error

**Comment by QB-nikolay-zolotarov** [comment] 2021-12-22 10:05
@MohammadAsef Hello,

This is Nikolay from QuickBlox support.

Our developers are investigating a similar issue. However, it may take some more time.

Once there is any news, I will let you know.

**Comment by MohammadAsef** [comment] 2021-12-24 17:18
ok

**Comment by QB-nikolay-zolotarov** [comment] 2022-02-10 11:58
@MohammadAsef According to our developers, the issue with sending messages should be resolved in the new version of the SDK:
https://pub.dev/packages/quickblox_sdk/changelog#065-beta
Please update it and let us know if the issue is resolved.

**Closed** 2023-01-11 10:13 UTC
